export const dummyData = [
  {
    title: 'Duck Rumaki',
    image: '../../../assets/icons/dummyImg.png',
    pricePerServing: 29.44,
    readyInMinutes: 45,
    servings: 24,
  },
  {
    title: 'Garlic Parmesan Chicken',
    image: 'https://spoonacular.com/recipeImages/715497-312x231.jpg',
    pricePerServing: 34.56,
    readyInMinutes: 50,
    servings: 4,
  },
  {
    title: 'Classic Margherita Pizza',
    image: 'https://spoonacular.com/recipeImages/715415-312x231.jpg',
    pricePerServing: 18.34,
    readyInMinutes: 30,
    servings: 2,
  },
  {
    title: 'Vegan Chocolate Cake',
    image: 'https://spoonacular.com/recipeImages/716426-312x231.jpg',
    pricePerServing: 50.23,
    readyInMinutes: 75,
    servings: 8,
  },
  {
    title: 'Spicy Thai Noodles',
    image: 'https://spoonacular.com/recipeImages/716627-312x231.jpg',
    pricePerServing: 15.99,
    readyInMinutes: 25,
    servings: 3,
  },
  {
    title: 'Quinoa Salad with Vegetables',
    image: 'https://spoonacular.com/recipeImages/782601-312x231.jpg',
    pricePerServing: 12.45,
    readyInMinutes: 20,
    servings: 2,
  },
  {
    title: 'Beef Bourguignon',
    image: 'https://spoonacular.com/recipeImages/794349-312x231.jpg',
    pricePerServing: 45.88,
    readyInMinutes: 120,
    servings: 6,
  },
];
